controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

login:
    path: /api/login

register:
  path: /api/user
  controller: App\Controller\UserController::create
  methods: POST

user:
  path: /api/user
  controller: App\Controller\UserController::show
  methods: GET

create-product:
  path: /api/product
  controller: App\Controller\ProductController::create
  methods: POST

get-product:
  path: /api/product/{id}
  controller: App\Controller\ProductController::show
  methods: GET
