controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

login:
    path: /api/login

register:
  path: /api/user
  controller: App\Controller\UserController::create
  methods: POST

user:
  path: /api/user
  controller: App\Controller\UserController::show
  methods: GET

create-product:
  path: /api/product
  controller: App\Controller\ProductController::create
  methods: POST

get-product:
  path: /api/product/{id}
  controller: App\Controller\ProductController::show
  methods: GET

create-order:
  path: /api/order
  controller: App\Controller\OrderController::create
  methods: POST

list-orders:
  path: /api/orders
  controller: App\Controller\OrderController::list
  methods: GET

get-order:
  path: /api/order/{id}
  controller: App\Controller\OrderController::show
  methods: GET

update-order:
  path: /api/order/{id}
  controller: App\Controller\OrderController::update
  methods: PUT
